### ISSUE TITLE
Partnerize mobile SDK framework does not include an arm64 slice for the simulator on M1

### ISSUE THREAD

**Issue by rdingman** [PerformanceHorizonGroup/partnerize-mobile-sdk-ios#8]
For projects that use Partnerize, you cannot build and run on the simulator on an Apple M1 laptop because the xcframework does not include a slice for arm64 on the simulator.

**Comment by daliad007** [comment]
Hello,

This is our last dependency that we have left in our project that is excluding arm64. Can this be updated? It forces us to continue to use Rosetta which we want to stop using.

Don't know if either @sam-miller-partnerize, @partnerizeJosh or @partnerizemark could give an idea about when this could come as an update? Thank you

**Comment by sam-miller-partnerize** [comment]
Hi @daliad007 - Thanks for reaching out. We recently put out an update with M1 support to the SDK (2.1.3) which can be manually downloaded from this repo, installed via cocoa pods, or via Swift Package Manager. The SPM support was added during the 2.1.3 updates and can be accessed here:

https://github.com/PerformanceHorizonGroup/partnerize-mobile-sdk-ios-spm

Please let me know if you have any more problems.

Thanks,

**Comment by daliad007** [comment]
Hey @sam-miller-partnerize Thank you, just updated via SPM and all working as expected 🙏

**Comment by sam-miller-partnerize** [comment]
Hi @daliad007 - No worries. Thanks for letting me know. I'll close this ticket but please let us know if there are any more issues.
